# Generated by Django 5.0.3 on 2024-03-16 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='News',
        ),
    ]
